version: "3"
services:

  wargame:
    image: wargame
    ports:
      - "80:80"
    volumes:
      - ./wargame:/var/www/html/

  wapi:
    image: wapi
    ports:
      - "8080:80"
    volumes:
      - ./wapi:/var/www/html