version: "3"
services:

  wargame:
    image: wargame
    ports:
      - "80:80"
    networks:
      - inter_service_net
    volumes:
      - ./wargame:/var/www/html/
    depends_on:
      - wapi
      - wsmtp

  wapi:
    image: wapi
    networks:
      - inter_service_net
    volumes:
      - ./wapi:/var/www/html

  wsmtp:
    image: namshi/smtp
    networks:
      - inter_service_net

networks:
  inter_service_net:
    internal: true