version: "3"
services:

  wargame:
    image: wargame
    ports:
      - "80:80"
    networks:
      - inter_service_net
    volumes:
      - ./wargame:/var/www/html/

  wapi:
    image: wapi
    ports:
      - "8080:80"
    networks:
      - inter_service_net
    volumes:
      - ./wapi:/var/www/html

networks:
  inter_service_net:
    driver: bridge